INSERT INTO AUTH_APP_USERS (APP_USER_NAME, APP_USER_FIRST_NAME, APP_USER_LAST_NAME, APP_USER_COMMENTS, APP_USER_ACTIVE_YN) VALUES ('PIFSC.ITS.TEST', 'ITS', 'Testing Account', '', 'Y');

INSERT INTO AUTH_APP_USER_GROUPS (APP_USER_ID, APP_GROUP_ID) VALUES ((SELECT APP_USER_ID FROM AUTH_APP_USERS WHERE APP_USER_NAME = 'PIFSC.ITS.TEST'), (SELECT APP_GROUP_ID FROM AUTH_APP_GROUPS WHERE APP_GROUP_CODE = 'DATA_ADMIN'));
