INSERT INTO AUTH_APP_USERS (APP_USER_NAME, APP_USER_COMMENTS, APP_USER_ACTIVE_YN) VALUES ('jesse.abdul', '', 'Y');
INSERT INTO AUTH_APP_USERS (APP_USER_NAME, APP_USER_COMMENTS, APP_USER_ACTIVE_YN) VALUES ('michael.akridge', '', 'Y');
INSERT INTO AUTH_APP_USERS (APP_USER_NAME, APP_USER_COMMENTS, APP_USER_ACTIVE_YN) VALUES ('erin.reed', '', 'Y');
INSERT INTO AUTH_APP_USERS (APP_USER_NAME, APP_USER_COMMENTS, APP_USER_ACTIVE_YN) VALUES ('kevin.trick', '', 'Y');
INSERT INTO AUTH_APP_USERS (APP_USER_NAME, APP_USER_COMMENTS, APP_USER_ACTIVE_YN) VALUES ('booke.olenski', '', 'Y');

INSERT INTO AUTH_APP_GROUPS (APP_GROUP_NAME, APP_GROUP_CODE, APP_GROUP_DESC) VALUES ('Administrators', 'DATA_ADMIN', 'Administrative users that can edit data for any division/program');


INSERT INTO AUTH_APP_USER_GROUPS (APP_USER_ID, APP_GROUP_ID) VALUES ((SELECT APP_USER_ID FROM AUTH_APP_USERS WHERE APP_USER_NAME = 'jesse.abdul'), (SELECT APP_GROUP_ID FROM AUTH_APP_GROUPS WHERE APP_GROUP_CODE = 'DATA_ADMIN'));
INSERT INTO AUTH_APP_USER_GROUPS (APP_USER_ID, APP_GROUP_ID) VALUES ((SELECT APP_USER_ID FROM AUTH_APP_USERS WHERE APP_USER_NAME = 'michael.akridge'), (SELECT APP_GROUP_ID FROM AUTH_APP_GROUPS WHERE APP_GROUP_CODE = 'DATA_ADMIN'));
INSERT INTO AUTH_APP_USER_GROUPS (APP_USER_ID, APP_GROUP_ID) VALUES ((SELECT APP_USER_ID FROM AUTH_APP_USERS WHERE APP_USER_NAME = 'erin.reed'), (SELECT APP_GROUP_ID FROM AUTH_APP_GROUPS WHERE APP_GROUP_CODE = 'DATA_ADMIN'));
INSERT INTO AUTH_APP_USER_GROUPS (APP_USER_ID, APP_GROUP_ID) VALUES ((SELECT APP_USER_ID FROM AUTH_APP_USERS WHERE APP_USER_NAME = 'kevin.trick'), (SELECT APP_GROUP_ID FROM AUTH_APP_GROUPS WHERE APP_GROUP_CODE = 'DATA_ADMIN'));
INSERT INTO AUTH_APP_USER_GROUPS (APP_USER_ID, APP_GROUP_ID) VALUES ((SELECT APP_USER_ID FROM AUTH_APP_USERS WHERE APP_USER_NAME = 'booke.olenski'), (SELECT APP_GROUP_ID FROM AUTH_APP_GROUPS WHERE APP_GROUP_CODE = 'DATA_ADMIN'));
