CREATE OR REPLACE SYNONYM CCD_CRUISE_DELIM_V FOR CEN_CRUISE.CCD_CRUISE_DELIM_V;
CREATE OR REPLACE SYNONYM CCD_CRUISE_LEG_DELIM_V FOR CEN_CRUISE.CCD_CRUISE_LEG_DELIM_V ;
CREATE OR REPLACE SYNONYM CCD_CRUISE_LEG_V FOR CEN_CRUISE.CCD_CRUISE_LEG_V ;
CREATE OR REPLACE SYNONYM CCD_CRUISE_SUMM_V FOR CEN_CRUISE.CCD_CRUISE_SUMM_V ;
CREATE OR REPLACE SYNONYM CCD_CRUISE_V FOR CEN_CRUISE.CCD_CRUISE_V ;
CREATE OR REPLACE SYNONYM CCD_LEG_DELIM_V FOR CEN_CRUISE.CCD_LEG_DELIM_V ;
CREATE OR REPLACE SYNONYM CCD_LEG_V FOR CEN_CRUISE.CCD_LEG_V ;
CREATE OR REPLACE SYNONYM CCD_LEG_AGG_V FOR CEN_CRUISE.CCD_LEG_AGG_V ;

CREATE OR REPLACE SYNONYM CCD_DATA_SETS_V FOR CEN_CRUISE.CCD_DATA_SETS_V ;
CREATE OR REPLACE SYNONYM CCD_LEG_DATA_SETS_V FOR CEN_CRUISE.CCD_LEG_DATA_SETS_V ;

CREATE OR REPLACE SYNONYM CCD_CRUISE_LEGS FOR CEN_CRUISE.CCD_CRUISE_LEGS;
CREATE OR REPLACE SYNONYM CCD_CRUISES FOR CEN_CRUISE.CCD_CRUISES;
CREATE OR REPLACE SYNONYM CCD_LEG_ALIASES FOR CEN_CRUISE.CCD_LEG_ALIASES;
CREATE OR REPLACE SYNONYM CCD_CRUISE_PKG FOR CEN_CRUISE.CCD_CRUISE_PKG;
CREATE OR REPLACE SYNONYM CCD_CRUISE_LEG_DATA_SETS_V FOR CEN_CRUISE.CCD_CRUISE_LEG_DATA_SETS_V;
CREATE OR REPLACE SYNONYM CCD_CRUISE_LEG_DATA_SETS_MIN_V FOR CEN_CRUISE.CCD_CRUISE_LEG_DATA_SETS_MIN_V;