CREATE OR REPLACE SYNONYM CEN_UTIL_PKG FOR CEN_UTILS.CEN_UTIL_PKG;
CREATE OR REPLACE SYNONYM CEN_UTIL_ARRAY_PKG FOR CEN_UTILS.CEN_UTIL_ARRAY_PKG;
CREATE OR REPLACE SYNONYM ODS_INP_DATASET_SCORING FOR PICDM.ODS_INP_DATASET_SCORING;
CREATE OR REPLACE SYNONYM DS_CUST_FLD_PKG_LOG_FILES_V FOR PICDM.DS_CUST_FLD_PKG_LOG_FILES_V;
