SELECT
TGT_SPP_ESA_NAME, TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where TGT_SPP_ESA_ID IN
(

	SELECT DISTINCT TGT_SPP_ESA_ID
	FROM
	(SELECT TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where ((:P220_ESA_SHOW_FILT_LIST = 'Y' OR :P220_ESA_SHOW_FILT_LIST IS NULL) AND APP_SHOW_OPT_YN = 'Y') OR (:P220_ESA_SHOW_FILT_LIST = 'N')

	UNION
	SELECT TGT_SPP_ESA_ID from CEN_CRUISE.CCD_CRUISE_SPP_ESA where cruise_id = :P220_CRUISE_ID)
)

ORDER BY UPPER(TGT_SPP_ESA_NAME)






--trying to log and also add the ID list in the list of species that is returned
DECLARE
    V_SQL VARCHAR2(4000);
    V_PROC_RETURN_CODE PLS_INTEGER;

BEGIN

    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of V_SQL is: '||V_SQL, V_PROC_RETURN_CODE);


V_SQL := 'SELECT
TGT_SPP_ESA_NAME, TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where TGT_SPP_ESA_ID IN
(

	SELECT DISTINCT TGT_SPP_ESA_ID
	FROM
	(SELECT TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where ((:P220_ESA_SHOW_FILT_LIST = ''Y'' OR :P220_ESA_SHOW_FILT_LIST IS NULL) AND APP_SHOW_OPT_YN = ''Y'') OR (:P220_ESA_SHOW_FILT_LIST = ''N'')

	UNION
	SELECT TGT_SPP_ESA_ID from CEN_CRUISE.CCD_CRUISE_SPP_ESA where cruise_id = :P220_CRUISE_ID

    UNION
    SELECT TGT_SPP_ESA_ID from CEN_CRUISE.CCD_TGT_SPP_ESA where TGT_SPP_ESA_ID IN ('||:P220_TGT_ESA_SPP_SHUTTLE||')
    )
)

ORDER BY UPPER(TGT_SPP_ESA_NAME)';




RETURN V_SQL;


END;



--working version without including the shuttle values

DECLARE
    V_TEMP_SQL VARCHAR2(4000);
    V_PROC_RETURN_CODE PLS_INTEGER;

BEGIN


    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of P220_CRUISE_ID is: '||:P220_CRUISE_ID, V_PROC_RETURN_CODE);
    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of P220_ESA_SHOW_FILT_LIST is: '||:P220_ESA_SHOW_FILT_LIST, V_PROC_RETURN_CODE);
    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of P220_TGT_ESA_SPP_SHUTTLE is: '||:P220_TGT_ESA_SPP_SHUTTLE, V_PROC_RETURN_CODE);


V_TEMP_SQL := 'SELECT
TGT_SPP_ESA_NAME, TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where TGT_SPP_ESA_ID IN
(

	SELECT DISTINCT TGT_SPP_ESA_ID
	FROM
	(SELECT TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where ((:P220_ESA_SHOW_FILT_LIST = ''Y'' OR :P220_ESA_SHOW_FILT_LIST IS NULL) AND APP_SHOW_OPT_YN = ''Y'') OR (:P220_ESA_SHOW_FILT_LIST = ''N'')

	UNION
	SELECT TGT_SPP_ESA_ID from CEN_CRUISE.CCD_CRUISE_SPP_ESA where cruise_id = :P220_CRUISE_ID)
)

ORDER BY UPPER(TGT_SPP_ESA_NAME)';


    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of V_SQL is: '||V_TEMP_SQL, V_PROC_RETURN_CODE);


RETURN V_TEMP_SQL;


END;



--latest attempt for a dynamic WHERE clause:

DECLARE
   l_selected apex_application_global.vc_arr2;
   V_TEMP_SQL VARCHAR2(4000);
    V_PROC_RETURN_CODE PLS_INTEGER;

    V_QUERY_FRAG VARCHAR2(4000) := NULL;

BEGIN


    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of P220_CRUISE_ID is: '||:P220_CRUISE_ID, V_PROC_RETURN_CODE);
    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of P220_ESA_SHOW_FILT_LIST is: '||:P220_ESA_SHOW_FILT_LIST, V_PROC_RETURN_CODE);
    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of P220_TGT_ESA_SPP_SHUTTLE is: '||:P220_TGT_ESA_SPP_SHUTTLE, V_PROC_RETURN_CODE);



    l_selected := apex_util.string_to_table(:P220_TGT_ESA_SPP_SHUTTLE);

   for i in 1..l_selected.count loop

        CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The current value of ESA Target Species is: '||l_selected(i), V_PROC_RETURN_CODE);

        IF (i = 0) THEN
            V_QUERY_FRAG := '(TGT_SPP_ESA_ID  = '||l_selected(i)||')';


        ELSE
            V_QUERY_FRAG := V_QUERY_FRAG||' OR (TGT_SPP_ESA_ID  = '||l_selected(i)||')';
        END IF;
    end loop;

    IF (V_QUERY_FRAG IS NOT NULL) THEN

        V_QUERY_FRAG := 'UNION SELECT TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where '||V_QUERY_FRAG;

    END IF;


V_TEMP_SQL := 'SELECT
TGT_SPP_ESA_NAME, TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where TGT_SPP_ESA_ID IN
(

	SELECT DISTINCT TGT_SPP_ESA_ID
	FROM
	(SELECT TGT_SPP_ESA_ID FROM CEN_CRUISE.CCD_TGT_SPP_ESA where ((:P220_ESA_SHOW_FILT_LIST = ''Y'' OR :P220_ESA_SHOW_FILT_LIST IS NULL) AND APP_SHOW_OPT_YN = ''Y'') OR (:P220_ESA_SHOW_FILT_LIST = ''N'')

	UNION
	SELECT TGT_SPP_ESA_ID from CEN_CRUISE.CCD_CRUISE_SPP_ESA where cruise_id = :P220_CRUISE_ID
    '||')
)

ORDER BY UPPER(TGT_SPP_ESA_NAME)';


    CEN_CRUISE.DB_LOG_PKG.ADD_LOG_ENTRY('DEBUG', 'PL/SQL returning SQL Query for ESA Target Species Shuttle', 'The value of V_SQL is: '||V_TEMP_SQL, V_PROC_RETURN_CODE);


RETURN V_TEMP_SQL;


END;
