--CCD_INTEG_ROLE
grant select on CCD_CRUISE_DELIM_V to CCD_INTEG_ROLE;
grant select on CCD_CRUISE_LEG_DELIM_V to CCD_INTEG_ROLE;
grant select on CCD_CRUISE_LEG_V to CCD_INTEG_ROLE;
grant select on CCD_CRUISE_SUMM_V to CCD_INTEG_ROLE;
grant select on CCD_CRUISE_V to CCD_INTEG_ROLE;
grant select on CCD_LEG_DELIM_V to CCD_INTEG_ROLE;
grant select on CCD_LEG_V to CCD_INTEG_ROLE;
grant select on CCD_LEG_AGG_V to CCD_INTEG_ROLE;
grant select on CCD_DATA_SETS_V to CCD_INTEG_ROLE;
grant select on CCD_LEG_DATA_SETS_V to CCD_INTEG_ROLE;
grant select on CCD_CRUISE_LEGS to CCD_INTEG_ROLE;
grant select on CCD_CRUISES to CCD_INTEG_ROLE;
grant select on CCD_LEG_ALIASES to CCD_INTEG_ROLE;
grant execute on CCD_CRUISE_PKG to CCD_INTEG_ROLE;
grant select on CCD_CRUISE_LEG_DATA_SETS_V TO CCD_INTEG_ROLE;
grant select on CCD_CRUISE_LEG_DATA_SETS_MIN_V TO CCD_INTEG_ROLE;

--CCD_APP_ROLE
grant execute on CCD_CRUISE_PKG to CCD_APP_ROLE;
grant execute on DB_LOG_PKG to CCD_APP_ROLE;
grant execute on CUST_ERR_PKG to CCD_APP_ROLE;


grant select on CCD_CRUISE_SUMM_V to CCD_APP_ROLE;
grant select on CCD_CRUISE_DELIM_V to CCD_APP_ROLE;
grant select on CCD_CRUISE_LEG_DELIM_V to CCD_APP_ROLE;
grant select on CCD_CRUISE_LEG_V to CCD_APP_ROLE;
grant select on CCD_CRUISE_V to CCD_APP_ROLE;
grant select on CCD_CRUISE_AGG_V to CCD_APP_ROLE;
grant select on CCD_DATA_SETS_V to CCD_APP_ROLE;
grant select on CCD_LEG_DELIM_V to CCD_APP_ROLE;
grant select on CCD_LEG_V to CCD_APP_ROLE;



grant insert, delete, update, select on CCD_CRUISES to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_CRUISE_LEGS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_VESSELS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_PLAT_TYPES to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_LEG_GEAR to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_GEAR to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_LEG_ECOSYSTEMS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_REG_ECOSYSTEMS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_LEG_ALIASES to CCD_APP_ROLE;


grant insert, delete, update, select on CCD_REGIONS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_LEG_REGIONS to CCD_APP_ROLE;



grant insert, delete, update, select on CCD_SCI_CENTERS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SCI_CENTER_DIVS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_STD_SVY_NAMES to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SVY_FREQ to CCD_APP_ROLE;

grant insert, delete, update, select on CCD_CRUISE_EXP_SPP to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_CRUISE_LEGS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_CRUISE_SPP_ESA to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_CRUISE_SPP_FSSI to CCD_APP_ROLE;

grant insert, delete, update, select on CCD_CRUISE_SPP_MMPA to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_CRUISE_SVY_CATS to CCD_APP_ROLE;



grant insert, delete, update, select on CCD_TGT_SPP_ESA to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_TGT_SPP_FSSI to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_TGT_SPP_MMPA to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_TGT_SPP_OTHER to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_EXP_SPP_CATS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SVY_CATS to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SVY_TYPES to CCD_APP_ROLE;


grant insert, delete, update, select on CCD_GEAR_PRE to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_GEAR_PRE_OPTS to CCD_APP_ROLE;
grant select on CCD_GEAR_PRE_V to CCD_APP_ROLE;

grant insert, delete, update, select on CCD_REG_ECO_PRE to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_REG_ECO_PRE_OPTS to CCD_APP_ROLE;
grant select on CCD_REG_ECO_PRE_V to CCD_APP_ROLE;

grant insert, delete, update, select on CCD_REGION_PRE to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_REGION_PRE_OPTS to CCD_APP_ROLE;
grant select on CCD_REGION_PRE_V to CCD_APP_ROLE;






grant insert, delete, update, select on CCD_SVY_CAT_PRE to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SVY_CAT_PRE_OPTS to CCD_APP_ROLE;
grant select on CCD_SVY_CAT_PRE_V to CCD_APP_ROLE;


grant insert, delete, update, select on CCD_SPP_ESA_PRE to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SPP_ESA_PRE_OPTS to CCD_APP_ROLE;
grant select on CCD_SPP_ESA_PRE_V to CCD_APP_ROLE;




grant insert, delete, update, select on CCD_SPP_FSSI_PRE to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SPP_FSSI_PRE_OPTS to CCD_APP_ROLE;
grant select on CCD_SPP_FSSI_PRE_V to CCD_APP_ROLE;


grant insert, delete, update, select on CCD_SPP_MMPA_PRE to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SPP_MMPA_PRE_OPTS to CCD_APP_ROLE;
grant select on CCD_SPP_MMPA_PRE_V to CCD_APP_ROLE;


grant insert, delete, update, select on CCD_SPP_CAT_PRE to CCD_APP_ROLE;
grant insert, delete, update, select on CCD_SPP_CAT_PRE_OPTS to CCD_APP_ROLE;
grant select on CCD_SPP_CAT_PRE_V to CCD_APP_ROLE;



grant select on CCD_REG_ECO_PRE_DELIM_V to CCD_APP_ROLE;
grant select on CCD_REGION_PRE_DELIM_V to CCD_APP_ROLE;

grant select on CCD_SPP_CAT_PRE_DELIM_V to CCD_APP_ROLE;
grant select on CCD_SPP_ESA_PRE_DELIM_V to CCD_APP_ROLE;
grant select on CCD_SPP_FSSI_PRE_DELIM_V to CCD_APP_ROLE;
grant select on CCD_SPP_MMPA_PRE_DELIM_V to CCD_APP_ROLE;
grant select on CCD_SVY_CAT_PRE_DELIM_V to CCD_APP_ROLE;

grant select on CCD_GEAR_PRE_DELIM_V to CCD_APP_ROLE;


grant select on CCD_SCI_CENTER_DIV_V to CCD_APP_ROLE;

grant select on CCD_SCI_CENTER_DELIM_V to CCD_APP_ROLE;



grant select, update, delete on DVM_ISSUES to CCD_APP_ROLE;
grant select, delete on DVM_ISS_TYP_ASSOC to CCD_APP_ROLE;
grant select, delete on DVM_PTA_ISSUES to CCD_APP_ROLE;


grant select on dvm_iss_severity to CCD_APP_ROLE;
grant select on dvm_iss_types to CCD_APP_ROLE;
grant select on dvm_iss_res_types to CCD_APP_ROLE;

grant execute on DVM_PKG to CCD_APP_ROLE;
grant execute on CCD_DVM_PKG to CCD_APP_ROLE;
grant select on DVM_PTA_ISSUES_V to CCD_APP_ROLE;


grant select on CCD_CRUISE_SUMM_ISS_V to CCD_APP_ROLE;
grant select on CCD_CRUISE_ISS_SUMM_V to CCD_APP_ROLE;
grant select on CCD_QC_LEG_OVERLAP_V to CCD_APP_ROLE;


grant select, insert, update, delete on CCD_LEG_DATA_SETS to CCD_APP_ROLE;
grant select, insert, update, delete on CCD_DATA_SETS to CCD_APP_ROLE;
grant select, insert, update, delete on CCD_DATA_SET_STATUS to CCD_APP_ROLE;
grant select, insert, update, delete on CCD_DATA_SET_TYPES to CCD_APP_ROLE;


--initial page is view all cruises (including info about assoc legs)

--apex feedback form:
grant select on AFF_RESP_TYPES to CCD_APP_ROLE;
grant select, insert on AFF_RESPONSES to CCD_APP_ROLE;
grant select on AFF_RESPONSES_V to CCD_APP_ROLE;



grant select on CC_CONFIG_OPTIONS TO CCD_APP_ROLE;





--CCD_READ_ROLE:
GRANT SELECT ON AFF_RESPONSES TO MOUSS_READ_ROLE;
GRANT SELECT ON AFF_RESPONSES_V TO MOUSS_READ_ROLE;
GRANT SELECT ON AFF_RESP_TYPES TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CCDP_DEEP_COPY_CMP_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISES TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_AGG_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_EVAL_RPT_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_EVAL_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_RULES_RPT_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_RULES_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_RULE_EVAL_RPT_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_RULE_EVAL_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_EXP_SPP TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_ISS_SUMM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_LEGS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_AGG_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_DATA_SETS_MIN_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_DATA_SETS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_SPP_ESA TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_SPP_FSSI TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_SPP_MMPA TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_SUMM_ISS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_SUMM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_SVY_CATS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_CRUISE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_DATA_SETS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_DATA_SETS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_DATA_SET_STATUS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_DATA_SET_TYPES TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_EXP_SPP_CATS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_GEAR TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_GEAR_PRE TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_GEAR_PRE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_GEAR_PRE_OPTS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_GEAR_PRE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_AGG_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_ALIASES TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_DATA_SETS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_DATA_SETS_MIN_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_DATA_SETS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_ECOSYSTEMS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_ECOSYSTEMS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_GEAR TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_GEAR_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_REGIONS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_REGIONS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_LEG_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_PLAT_TYPES TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_QC_CRUISE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_QC_LEG_ALIAS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_QC_LEG_OVERLAP_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_QC_LEG_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REGIONS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REGION_PRE TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REGION_PRE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REGION_PRE_OPTS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REGION_PRE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REG_ECOSYSTEMS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REG_ECO_PRE TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REG_ECO_PRE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REG_ECO_PRE_OPTS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_REG_ECO_PRE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SCI_CENTERS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SCI_CENTER_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SCI_CENTER_DIVS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SCI_CENTER_DIV_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_CAT_PRE TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_CAT_PRE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_CAT_PRE_OPTS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_CAT_PRE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_ESA_PRE TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_ESA_PRE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_ESA_PRE_OPTS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_ESA_PRE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_FSSI_PRE TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_FSSI_PRE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_FSSI_PRE_OPTS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_FSSI_PRE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_MMPA_PRE TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_MMPA_PRE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_MMPA_PRE_OPTS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SPP_MMPA_PRE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_STD_SVY_NAMES TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SVY_CATS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SVY_CAT_PRE TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SVY_CAT_PRE_DELIM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SVY_CAT_PRE_OPTS TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SVY_CAT_PRE_V TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SVY_FREQ TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_SVY_TYPES TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_TGT_SPP_ESA TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_TGT_SPP_FSSI TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_TGT_SPP_MMPA TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_TGT_SPP_OTHER TO MOUSS_READ_ROLE;
GRANT SELECT ON CCD_VESSELS TO MOUSS_READ_ROLE;
GRANT SELECT ON CC_CONFIG_OPTIONS TO MOUSS_READ_ROLE;
GRANT SELECT ON CC_CONFIG_OPTIONS_HIST TO MOUSS_READ_ROLE;
GRANT SELECT ON CUST_ERR_CONSTR_MSG TO MOUSS_READ_ROLE;
GRANT SELECT ON DB_LOG_ENTRIES TO MOUSS_READ_ROLE;
GRANT SELECT ON DB_LOG_ENTRIES_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DB_LOG_ENTRY_TYPES TO MOUSS_READ_ROLE;
GRANT SELECT ON DB_UPGRADE_LOGS TO MOUSS_READ_ROLE;
GRANT SELECT ON DB_UPGRADE_LOGS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_CRITERIA_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_DATA_STREAMS TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_DATA_STREAMS_HIST TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_DATA_STREAMS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_DS_PTA_RULE_SETS_HIST_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_DS_PTA_RULE_SETS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISSUES TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISSUES_HIST TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISS_RES_TYPES TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISS_RES_TYPES_HIST TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISS_SEVERITY TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISS_SEVERITY_HIST TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISS_TYPES TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISS_TYPES_HIST TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_ISS_TYP_ASSOC TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_ISSUES TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_ISSUES_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_ISSUE_SUMM_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_ISS_TYPES_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_HIST TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_HIST_RPT_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_HIST_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_RPT_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_QC_MSG_MISS_FIELDS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_QC_OBJECTS TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_QC_OBJECTS_HIST TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_RULE_SETS TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_RULE_SETS_RPT_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_RULE_SETS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_STD_QC_ACT_RULE_SETS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_STD_QC_DS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_STD_QC_DS_VIEWS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_STD_QC_IND_FIELDS_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_STD_QC_ISS_TEMPL_V TO MOUSS_READ_ROLE;
GRANT SELECT ON DVM_STD_QC_MISS_CONFIG_V TO MOUSS_READ_ROLE;

--CCD_WRITE_ROLE:
GRANT SELECT, INSERT, UPDATE, DELETE ON AFF_RESPONSES TO MOUSS_WRITE_ROLE;
GRANT SELECT ON AFF_RESPONSES_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON AFF_RESP_TYPES TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CCDP_DEEP_COPY_CMP_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_CRUISES TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_AGG_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_EVAL_RPT_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_EVAL_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_RULES_RPT_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_RULES_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_RULE_EVAL_RPT_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_DVM_RULE_EVAL_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_CRUISE_EXP_SPP TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_ISS_SUMM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_CRUISE_LEGS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_AGG_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_DATA_SETS_MIN_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_DATA_SETS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_LEG_V TO MOUSS_WRITE_ROLE;
GRANT EXECUTE ON CCD_CRUISE_PKG TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_CRUISE_SPP_ESA TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_CRUISE_SPP_FSSI TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_CRUISE_SPP_MMPA TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_SUMM_ISS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_SUMM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_CRUISE_SVY_CATS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_CRUISE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_DATA_SETS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_DATA_SETS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_DATA_SET_STATUS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_DATA_SET_TYPES TO MOUSS_WRITE_ROLE;
GRANT EXECUTE ON CCD_DVM_PKG TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_EXP_SPP_CATS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_GEAR TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_GEAR_PRE TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_GEAR_PRE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_GEAR_PRE_OPTS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_GEAR_PRE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_LEG_AGG_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_LEG_ALIASES TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_LEG_DATA_SETS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_LEG_DATA_SETS_MIN_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_LEG_DATA_SETS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_LEG_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_LEG_ECOSYSTEMS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_LEG_ECOSYSTEMS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_LEG_GEAR TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_LEG_GEAR_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_LEG_REGIONS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_LEG_REGIONS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_LEG_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_PLAT_TYPES TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_QC_CRUISE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_QC_LEG_ALIAS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_QC_LEG_OVERLAP_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_QC_LEG_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_REGIONS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_REGION_PRE TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_REGION_PRE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_REGION_PRE_OPTS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_REGION_PRE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_REG_ECOSYSTEMS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_REG_ECO_PRE TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_REG_ECO_PRE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_REG_ECO_PRE_OPTS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_REG_ECO_PRE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SCI_CENTERS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SCI_CENTER_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SCI_CENTER_DIVS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SCI_CENTER_DIV_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SPP_CAT_PRE TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SPP_CAT_PRE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SPP_CAT_PRE_OPTS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SPP_CAT_PRE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SPP_ESA_PRE TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SPP_ESA_PRE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SPP_ESA_PRE_OPTS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SPP_ESA_PRE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SPP_FSSI_PRE TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SPP_FSSI_PRE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SPP_FSSI_PRE_OPTS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SPP_FSSI_PRE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SPP_MMPA_PRE TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SPP_MMPA_PRE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SPP_MMPA_PRE_OPTS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SPP_MMPA_PRE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_STD_SVY_NAMES TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SVY_CATS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SVY_CAT_PRE TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SVY_CAT_PRE_DELIM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SVY_CAT_PRE_OPTS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON CCD_SVY_CAT_PRE_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SVY_FREQ TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_SVY_TYPES TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_TGT_SPP_ESA TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_TGT_SPP_FSSI TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_TGT_SPP_MMPA TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_TGT_SPP_OTHER TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CCD_VESSELS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CC_CONFIG_OPTIONS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CC_CONFIG_OPTIONS_HIST TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON CUST_ERR_CONSTR_MSG TO MOUSS_WRITE_ROLE;
GRANT EXECUTE ON CUST_ERR_PKG TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DB_LOG_ENTRIES TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DB_LOG_ENTRIES_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DB_LOG_ENTRY_TYPES TO MOUSS_WRITE_ROLE;
GRANT EXECUTE ON DB_LOG_PKG TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DB_UPGRADE_LOGS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DB_UPGRADE_LOGS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_CRITERIA_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_DATA_STREAMS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_DATA_STREAMS_HIST TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_DATA_STREAMS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_DS_PTA_RULE_SETS_HIST_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_DS_PTA_RULE_SETS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISSUES TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISSUES_HIST TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISS_RES_TYPES TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISS_RES_TYPES_HIST TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISS_SEVERITY TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISS_SEVERITY_HIST TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISS_TYPES TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISS_TYPES_HIST TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_ISS_TYP_ASSOC TO MOUSS_WRITE_ROLE;
GRANT EXECUTE ON DVM_PKG TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_PTA_ISSUES TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_PTA_ISSUES_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_PTA_ISSUE_SUMM_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_PTA_ISS_TYPES_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_PTA_RULE_SETS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_PTA_RULE_SETS_HIST TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_HIST_RPT_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_HIST_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_RPT_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_PTA_RULE_SETS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_QC_MSG_MISS_FIELDS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_QC_OBJECTS TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_QC_OBJECTS_HIST TO MOUSS_WRITE_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON DVM_RULE_SETS TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_RULE_SETS_RPT_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_RULE_SETS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_STD_QC_ACT_RULE_SETS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_STD_QC_DS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_STD_QC_DS_VIEWS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_STD_QC_IND_FIELDS_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_STD_QC_ISS_TEMPL_V TO MOUSS_WRITE_ROLE;
GRANT SELECT ON DVM_STD_QC_MISS_CONFIG_V TO MOUSS_WRITE_ROLE;
