set define off;

/*

delete from ctd_cruise_aliases;
delete from ctd_cruises;
delete from ctd_rsrch_vessels;

*/

insert into ccd_vessels (vessel_name) values ('Townsend Cromwell');
insert into ccd_vessels (vessel_name) values ('Hi''ialakai');
insert into ccd_vessels (vessel_name) values ('Oscar Elton Sette');


insert into ccd_cruises (cruise_name, vessel_id) values ('HA1007', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HA1008', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HA1201', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI0401', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI0602', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI0604', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI0609', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI0610', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI0611', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI0701', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI1001', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('HI1101', (select vessel_id from ccd_vessels where vessel_name = 'Hi''ialakai'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0304', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0306', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0407', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0410', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0411', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0504', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0506', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0509', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0512', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0604', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0606', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0607', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0608', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0706', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('OES0908', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('SE1501', (select vessel_id from ccd_vessels where vessel_name = 'Oscar Elton Sette'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0005', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0009', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0011', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0012', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0108', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0109', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0110', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0111', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0201', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC0207', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC9905', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC9906', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC9908', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC9909', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));
insert into ccd_cruises (cruise_name, vessel_id) values ('TC9910', (select vessel_id from ccd_vessels where vessel_name = 'Townsend Cromwell'));




insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HA1007'), 'HA1007');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HA1008'), 'HA1008');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HA1201'), 'HA1201');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HA1201'), 'HA1201_LEGI');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HA1201'), 'HA1201_LEGII&III');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HA1201'), 'HA1201_LEGIV');				
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI0401'), 'HI0401');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI0401'), 'HI-04-01');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI0602'), 'HI0602');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI0604'), 'HI0604');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI0609'), 'HI0609');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI0610'), 'HI0610');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI0611'), 'HI0611');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI0701'), 'HI0701');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1001'), 'HI1001');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1001'), 'HI1001_LEGI');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1001'), 'HI1001_LEGII');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1001'), 'HI1001_LEGIII');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1001'), 'HI1001_allLegs');			
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1101'), 'HI1101');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1101'), 'HI1101_LEGI');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1101'), 'HI1101_LEGII');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1101'), 'HI1101_LEGIII');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1101'), 'HI1101_allLegs');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1101'), 'HA1101_LEGI');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1101'), 'HA1101_LEGII');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'HI1101'), 'HA1101_LEGIII');
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0304'), 'OES0304');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0304'), 'OS-03-04');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0306'), 'OES0306');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0306'), 'OS-03-06');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0407'), 'OES0407');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0407'), 'OS-04-07');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0410'), 'OES0410');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0410'), 'OS-04-10');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0411'), 'OES0411');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0411'), 'OS-04-11');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0504'), 'OES0504');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0504'), 'OS-05-04');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0504'), 'OS0504');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0506'), 'OES0506');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0506'), 'OS-05-06');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0506'), 'OS0506');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0509'), 'OES0509');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0509'), 'OS-05-09');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0509'), 'OS0509');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0512'), 'OES0512');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0512'), 'OS-05-12');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0512'), 'OS0512');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0604'), 'OES0604');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0604'), 'OS-06-04');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0604'), 'OS0604');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0606'), 'OES0606');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0606'), 'OS-06-06');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0606'), 'OS0606');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0607'), 'OES0607');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0607'), 'OS-06-07');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0607'), 'OS0607');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0608'), 'OES0608');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0608'), 'OS-06-08');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0608'), 'OS0608');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0706'), 'OES0706');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0706'), 'OS-07-06');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0706'), 'OS0706');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0908'), 'OES0908');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0908'), 'OES0908_LEGI');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0908'), 'OES0908_LEGII');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0908'), 'OES0908_allLegs');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'OES0908'), 'SE-09-08');			
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'SE1501'), 'SE1501');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'SE1501'), 'SE15-01');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'SE1501'), 'SE-15-01');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'SE1501'), '15_01');				
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0005'), 'TC0005');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0005'), 'TC_00_05');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0009'), 'TC0009');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0009'), 'TC-00-09');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0011'), 'TC0011');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0011'), 'TC-00-11');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0012'), 'TC0012');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0012'), 'TC-00-12');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0108'), 'TC0108');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0108'), 'TC-01-08');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0109'), 'TC0109');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0109'), 'TC-01-09');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0110'), 'TC0110');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0110'), 'TC-01-10');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0111'), 'TC0111');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0111'), 'TC-01-11');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0201'), 'TC0201');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0201'), 'TC-02-01');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0201'), 'TC0201_LEGII');					
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0207'), 'TC0207');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC0207'), 'TC-02-07');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9905'), 'TC9905');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9905'), '99-05');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9906'), 'TC9906');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9906'), '99-06');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9908'), 'TC9908');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9908'), 'TC99-08');						
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9909'), 'TC9909');							
insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9910'), 'TC9910');	insert into ccd_cruise_aliases (cruise_id, CRUISE_ALIAS_NAME) values ((select cruise_id from ccd_cruises where cruise_name = 'TC9910'), 'TC-99-10');						
