INSERT INTO DVM_DATA_STREAMS (DATA_STREAM_CODE, DATA_STREAM_NAME, DATA_STREAM_DESC, DATA_STREAM_PAR_TABLE)
VALUES ('CCD', 'CCD Data', 'Cruise data', 'CCD_CRUISES');



insert into DVM_QC_OBJECTS (OBJECT_NAME, QC_OBJ_ACTIVE_YN, QC_SORT_ORDER) VALUES ('CCD_QC_LEG_OVERLAP_V', 'Y', 20);

insert into DVM_QC_OBJECTS (OBJECT_NAME, QC_OBJ_ACTIVE_YN, QC_SORT_ORDER) VALUES ('CCD_QC_CRUISE_V', 'Y', 5);

insert into DVM_QC_OBJECTS (OBJECT_NAME, QC_OBJ_ACTIVE_YN, QC_SORT_ORDER) VALUES ('CCD_QC_LEG_V', 'Y', 10);

insert into DVM_QC_OBJECTS (OBJECT_NAME, QC_OBJ_ACTIVE_YN, QC_SORT_ORDER) VALUES ('CCD_QC_LEG_ALIAS_V', 'Y', 15);



INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Abnormally High Cruise Days at Sea', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) and number of Legs ([NUM_LEGS]) has an abnormally high number ( > 120) of Days at Sea ([CRUISE_DAS])', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'WARN_CRUISE_DAS_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'WARN'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Cruise is too long (DAS based on start and end dates) > 120 days');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Abnormally High Cruise Length', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) and number of Legs ([NUM_LEGS]) is abnormally long ( > 160) days based on the date range ([CRUISE_LEN_DAYS] days) ', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'WARN_CRUISE_DATE_RNG_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'WARN'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Cruise is too long (based on the cruise start and end dates even if the leg DAS is not over the threshold) > 160 days');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Invalid Copied Cruise Name', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) has "(copy)" in the Cruise Name, this should be renamed', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'INV_CRUISE_NAME_COPY_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'The Cruise Name contains "(copy)" which indicates it was created using the "Deep Copy" feature and should be renamed');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Invalid Cruise Days at Sea', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) and number of Legs ([NUM_LEGS]) has an invalid number ( > 240) of Days at Sea ([CRUISE_DAS])', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'ERR_CRUISE_DAS_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Cruise is too long (DAS based on start and end dates) > 240 days');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Invalid Cruise Length', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) and number of Legs ([NUM_LEGS]) has an invalid length ( > 280) days based on the date range ([CRUISE_LEN_DAYS] days) ', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'ERR_CRUISE_DATE_RNG_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Cruise is too long (based on the cruise start and end dates even if the leg DAS is not over the threshold) > 280 days');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Missing Cruise Primary Survey Category', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) and number of Legs ([NUM_LEGS]) does not have at least one Primary Survey Category defined for it', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'MISS_PRIM_SVY_CAT_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'WARN'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'The Cruise does not have a Primary Survey Category defined for it');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Missing Standard Survey Name', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) does not have a Standard Survey Name defined for it', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'MISS_STD_SVY_NAME_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Both the Cruise Standard Survey Name fields were not populated, one or the other must be specified');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Invalid Copied Leg Alias Name', 'The Cruise ([CRUISE_NAME]) has a Cruise Leg ([LEG_NAME]) on the Vessel ([VESSEL_NAME]) with Start Date ([FORMAT_LEG_START_DATE]) and End Date ([FORMAT_LEG_END_DATE]) that has a Leg alias name ([LEG_ALIAS_NAME]) that contains "(copy)", this should be renamed', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_LEG_ALIAS_V'), 'INV_LEG_ALIAS_COPY_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'The Leg Alias Name contains "(copy)" which indicates it was created using the "Deep Copy" feature and should be renamed');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Cruise Leg Overlap', 'There are two legs for the same Cruise ([CRUISE_NAME1]) whose leg dates overlap; Cruise Leg 1: (Leg Name: [LEG_NAME1], Vessel: [VESSEL_NAME1], Start Date: [FORMAT_LEG_START_DATE1], End Date: [FORMAT_LEG_END_DATE1]), Leg 2: (Leg Name: [LEG_NAME2], Vessel: [VESSEL_NAME2], Start Date: [FORMAT_LEG_START_DATE2], End Date: [FORMAT_LEG_END_DATE2])', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_LEG_OVERLAP_V'), 'CRUISE_OVERLAP_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Two cruise legs that are associated with the same cruise have overlapping start/end dates, two legs for the same cruise cannot occur concurrently');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Vessel Leg Overlap', 'There are two legs for the same Vessel ([VESSEL_NAME1]) whose leg dates overlap; Leg 1: (Cruise: [CRUISE_NAME1], Leg Name: [LEG_NAME1], Start Date: [FORMAT_LEG_START_DATE1], End Date: [FORMAT_LEG_END_DATE1]), Leg 2: (Cruise: [CRUISE_NAME2], Leg Name: [LEG_NAME2], Start Date: [FORMAT_LEG_START_DATE2], End Date: [FORMAT_LEG_END_DATE2])', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_LEG_OVERLAP_V'), 'VESSEL_OVERLAP_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Two cruise legs that are associated with the same vessel have overlapping start/end dates, two legs for the same vessel cannot occur concurrently');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Abnormally High Leg Days at Sea', 'The Cruise ([CRUISE_NAME]) has a Cruise Leg ([LEG_NAME]) on the Vessel ([VESSEL_NAME]) with a Start Date ([FORMAT_LEG_START_DATE]) and End Date ([FORMAT_LEG_END_DATE]) that has an abnormally high number ( > 30) of Days at Sea ([LEG_DAS])', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_LEG_V'), 'WARN_LEG_DAS_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'WARN'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Leg is too long (DAS based on start and end dates) > 30 days');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Invalid Copied Leg Name', 'The Cruise ([CRUISE_NAME]) has a Cruise Leg ([LEG_NAME]) on the Vessel ([VESSEL_NAME]) with Start Date ([FORMAT_LEG_START_DATE]) and End Date ([FORMAT_LEG_END_DATE]) that has "(copy)" in the Leg Name, this should be renamed', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_LEG_V'), 'INV_LEG_NAME_COPY_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'The Leg Name contains "(copy)" which indicates it was created using the "Deep Copy" feature and should be renamed');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Invalid Leg Dates', 'The Cruise ([CRUISE_NAME]) has a Cruise Leg ([LEG_NAME]) on the Vessel ([VESSEL_NAME]) with a Start Date ([FORMAT_LEG_START_DATE]) and End Date ([FORMAT_LEG_END_DATE]) that are invalid, the Start Date occurs after the End Date', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_LEG_V'), 'INV_LEG_DATES_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'The Leg''s Start Date occurs after the End Date');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Invalid Leg Days at Sea', 'The Cruise ([CRUISE_NAME]) has a Cruise Leg ([LEG_NAME]) on the Vessel ([VESSEL_NAME]) with a Start Date ([FORMAT_LEG_START_DATE]) and End Date ([FORMAT_LEG_END_DATE]) that has an invalid number ( > 90) of Days at Sea ([LEG_DAS])', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_LEG_V'), 'ERR_LEG_DAS_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'Leg is too long (DAS based on start and end dates) > 90 days');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Missing Leg Gear', 'The Cruise ([CRUISE_NAME]) has a Cruise Leg ([LEG_NAME]) on the Vessel ([VESSEL_NAME]) with a Start Date ([FORMAT_LEG_START_DATE]) and End Date ([FORMAT_LEG_END_DATE]) that does not have at least one type of Gear defined for it', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_LEG_V'), 'MISS_GEAR_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'WARN'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'The Leg does not have any gear defined for it');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Invalid Cruise Name', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) has an invalid Cruise Name based on the required naming convention: {SN}-{YR}-{##} where {SN} is a valid NOAA ship name, {YR} is a two digit year with a leading zero, and {##} is a sequential number with a leading zero', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'INV_CRUISE_NAME_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'The cruise name does not follow the naming convention {SN}-{YR}-{##} where {SN} is a valid NOAA ship name, {YR} is a two digit year with a leading zero, and {##} is a sequential number with a leading zero');
INSERT INTO DVM_ERROR_TYPES (ERR_TYPE_NAME, ERR_TYPE_COMMENT_TEMPLATE, QC_OBJECT_ID, IND_FIELD_NAME, ERR_SEVERITY_ID, DATA_STREAM_ID, ERR_TYPE_ACTIVE_YN, ERR_TYPE_DESC) VALUES ('Mismatched Cruise Name and Fiscal Year', 'The Cruise ([CRUISE_NAME]) with Start Date ([FORMAT_CRUISE_START_DATE]) and End Date ([FORMAT_CRUISE_END_DATE]) has a valid Cruise Name based on the required naming convention ({SN}-{YR}-{##}) but the extracted {YR} value ([CRUISE_NAME_FY]) does not match the truncated Cruise''s Fiscal Year value ([CRUISE_FISC_YEAR_TRUNC])', (SELECT QC_OBJECT_ID FROM DVM_QC_OBJECTS WHERE OBJECT_NAME = 'CCD_QC_CRUISE_V'), 'INV_CRUISE_NAME_FY_YN', (SELECT ERR_SEVERITY_ID FROM DVM_ERR_SEVERITY WHERE ERR_SEVERITY_CODE = 'FATAL'), (SELECT data_stream_id from DVM_data_streams where data_stream_code = 'CCD'), 'Y', 'The cruise name follows the naming convention {SN}-{YR}-{##} but {YR} does not match the Cruise Fiscal Year based on the first leg''s start date');


/*
delete from dvm_error_types;
delete from dvm_qc_objects;
delete from DVM_data_streams;
*/
