/*
 delete from ccd_data_sets;
 delete from ccd_data_set_types;
 delete from ccd_data_set_status;




 **/



INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('MOUSS Video', 'Modular Optical Underwater Survey System', 'https://inport.nmfs.noaa.gov/inport/item/51818');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('CTD', 'Conductivity, Temperature, and Depth', 'https://inport.nmfs.noaa.gov/inport/item/7602');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('Water Samples', 'Discrete Water Samples', '');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('Coral Belt', 'Belt Transect Survey', '');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('Fish REA', 'Fish Rapid Ecological Assessment Survey', 'https://inport.nmfs.noaa.gov/inport/item/5565');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('ARMS', 'Autonomous Reef Monitoring System', 'https://inport.nmfs.noaa.gov/inport/item/36038');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('Fish Towed Diver', 'Fish Towed Diver Survey', 'https://inport.nmfs.noaa.gov/inport/item/34521');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('Benthic Towed Diver', 'Benthic Towed Diver Survey', 'https://inport.nmfs.noaa.gov/inport/item/35618');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('CAU', 'Calcification Accretion Units', 'https://inport.nmfs.noaa.gov/inport/item/26945');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('Midwater Trawling', 'Midwater Trawling Survey', '');
INSERT INTO CCD_data_set_types (data_set_type_name, data_set_type_desc, data_set_type_doc_url) values ('Active Acoustics', 'Active Acoustics Survey', '');



insert into ccd_data_set_status (STATUS_CODE, STATUS_NAME, STATUS_DESC, STATUS_COLOR) values ('COL', 'Data Collection', 'Data is being collected', '#e76e3c');
insert into ccd_data_set_status (STATUS_CODE, STATUS_NAME, STATUS_DESC, STATUS_COLOR) values ('PR', 'Data Processing', 'Data has been collected and the data is currently being processed', '#4b6a88');
insert into ccd_data_set_status (STATUS_CODE, STATUS_NAME, STATUS_DESC, STATUS_COLOR) values ('QC', 'Quality Control', 'Data has been processed and data quality control is currently being evaluated and issues are being resolved and/or annotated', '#0000e0');
insert into ccd_data_set_status (STATUS_CODE, STATUS_NAME, STATUS_DESC, STATUS_COLOR) values ('IA', 'Internally Accessible', 'Data has been quality controlled and it is currently internally accessible', '#1e90ff');
insert into ccd_data_set_status (STATUS_CODE, STATUS_NAME, STATUS_DESC, STATUS_COLOR) values ('PA', 'Publicly Accessible', 'Data has been quality controlled and it is currently publicly accessible', '#005555');
insert into ccd_data_set_status (STATUS_CODE, STATUS_NAME, STATUS_DESC, STATUS_COLOR) values ('ARCH', 'Archived', 'Data has been quality controlled and it is currently archived', '#00aa00');


insert into ccd_data_sets (DATA_SET_DESC, DATA_SET_TYPE_ID, DATA_SET_DOI, DATA_SET_INPORT_URL, DATA_SET_ACCESS_URL, DATA_SET_ARCHIVE_URL, CRUISE_LEG_ID, DATA_SET_STATUS_ID) values ('This accession contains the Modular Optical Underwater Survey System (MOUSS) stereo video data from SE-17-02 (03/09/2017 - 03/22/2017) collected around the Main Hawaiian Islands (MHI) for the stock assessment of the deep-7 bottomfish species. Each video is fifteen minutes from the MOUSS touchdown on the seafloor as that is the literature based standard for deep-7 species. The products also include depth and temperature data collected using Temperature Depth Recorder (TDR) along with temporal and spatial information.', (SELECT DATA_SET_TYPE_ID FROM CCD_DATA_SET_TYPES WHERE DATA_SET_TYPE_NAME = 'MOUSS Video'), '', 'https://inport.nmfs.noaa.gov/inport/item/51818', '', '', (SELECT CRUISE_LEG_ID FROM CCD_CRUISE_LEGS where leg_name = 'SE-17-02'), (SELECT DATA_SET_STATUS_ID FROM CCD_DATA_SET_STATUS where status_code = 'QC'));
insert into ccd_data_sets (DATA_SET_DESC, DATA_SET_TYPE_ID, DATA_SET_DOI, DATA_SET_INPORT_URL, DATA_SET_ACCESS_URL, DATA_SET_ARCHIVE_URL, CRUISE_LEG_ID, DATA_SET_STATUS_ID) values ('This accession contains the Modular Optical Underwater Survey System (MOUSS) stereo video data from SE-17-07 (10/20/2017-11/03/2017) collected around the Main Hawaiian Islands (MHI) for the stock assessment of the deep-7 bottomfish species. Each video is fifteen minutes from the MOUSS touchdown on the seafloor as that is the literature based standard for deep-7 species. The products also include depth and temperature data collected using Temperature Depth Recorder (TDR) along with temporal and spatial information.', (SELECT DATA_SET_TYPE_ID FROM CCD_DATA_SET_TYPES WHERE DATA_SET_TYPE_NAME = 'MOUSS Video'), '', 'https://inport.nmfs.noaa.gov/inport/item/51818', '', '', (SELECT CRUISE_LEG_ID FROM CCD_CRUISE_LEGS where leg_name = 'SE-17-07'), (SELECT DATA_SET_STATUS_ID FROM CCD_DATA_SET_STATUS where status_code = 'IA'));
insert into ccd_data_sets (DATA_SET_DESC, DATA_SET_TYPE_ID, DATA_SET_DOI, DATA_SET_INPORT_URL, DATA_SET_ACCESS_URL, DATA_SET_ARCHIVE_URL, CRUISE_LEG_ID, DATA_SET_STATUS_ID) values ('', (SELECT DATA_SET_TYPE_ID FROM CCD_DATA_SET_TYPES WHERE DATA_SET_TYPE_NAME = 'CTD'), '', 'https://inport.nmfs.noaa.gov/inport/item/7602', '', '', (SELECT CRUISE_LEG_ID FROM CCD_CRUISE_LEGS where leg_name = 'SE-15-01'), (SELECT DATA_SET_STATUS_ID FROM CCD_DATA_SET_STATUS where status_code = 'PA'));
insert into ccd_data_sets (DATA_SET_DESC, DATA_SET_TYPE_ID, DATA_SET_DOI, DATA_SET_INPORT_URL, DATA_SET_ACCESS_URL, DATA_SET_ARCHIVE_URL, CRUISE_LEG_ID, DATA_SET_STATUS_ID) values ('', (SELECT DATA_SET_TYPE_ID FROM CCD_DATA_SET_TYPES WHERE DATA_SET_TYPE_NAME = 'Water Samples'), '', 'https://inport.nmfs.noaa.gov/inport/item/25860', '', '', (SELECT CRUISE_LEG_ID FROM CCD_CRUISE_LEGS where leg_name = 'SE-15-01'), (SELECT DATA_SET_STATUS_ID FROM CCD_DATA_SET_STATUS where status_code = 'QC'));
insert into ccd_data_sets (DATA_SET_DESC, DATA_SET_TYPE_ID, DATA_SET_DOI, DATA_SET_INPORT_URL, DATA_SET_ACCESS_URL, DATA_SET_ARCHIVE_URL, CRUISE_LEG_ID, DATA_SET_STATUS_ID) values ('', (SELECT DATA_SET_TYPE_ID FROM CCD_DATA_SET_TYPES WHERE DATA_SET_TYPE_NAME = 'Midwater Trawling'), '', '', '', '', (SELECT CRUISE_LEG_ID FROM CCD_CRUISE_LEGS where leg_name = 'SE-15-01'), (SELECT DATA_SET_STATUS_ID FROM CCD_DATA_SET_STATUS where status_code = 'IA'));
insert into ccd_data_sets (DATA_SET_DESC, DATA_SET_TYPE_ID, DATA_SET_DOI, DATA_SET_INPORT_URL, DATA_SET_ACCESS_URL, DATA_SET_ARCHIVE_URL, CRUISE_LEG_ID, DATA_SET_STATUS_ID) values ('', (SELECT DATA_SET_TYPE_ID FROM CCD_DATA_SET_TYPES WHERE DATA_SET_TYPE_NAME = 'Active Acoustics'), '', 'https://inport.nmfs.noaa.gov/inport/item/2711', '', '', (SELECT CRUISE_LEG_ID FROM CCD_CRUISE_LEGS where leg_name = 'SE-15-01'), (SELECT DATA_SET_STATUS_ID FROM CCD_DATA_SET_STATUS where status_code = 'PA'));
insert into ccd_data_sets (DATA_SET_DESC, DATA_SET_TYPE_ID, DATA_SET_DOI, DATA_SET_INPORT_URL, DATA_SET_ACCESS_URL, DATA_SET_ARCHIVE_URL, CRUISE_LEG_ID, DATA_SET_STATUS_ID) values ('This accession contains the Modular Optical Underwater Survey System (MOUSS) stereo video data from SE-18-06 (10/17/2018 - 10/31/2018) collected around the Main Hawaiian Islands (MHI) for the stock assessment of the deep-7 bottomfish species. Each video is fifteen minutes from the MOUSS touchdown on the seafloor as that is the literature based standard for deep-7 species. The products also include depth and temperature data collected using Temperature Depth Recorder (TDR) along with temporal and spatial information.', (SELECT DATA_SET_TYPE_ID FROM CCD_DATA_SET_TYPES WHERE DATA_SET_TYPE_NAME = 'MOUSS Video'), '', '', '', '', (SELECT CRUISE_LEG_ID FROM CCD_CRUISE_LEGS where leg_name = 'SE-18-06'), (SELECT DATA_SET_STATUS_ID FROM CCD_DATA_SET_STATUS where status_code = 'COL'));

insert into ccd_data_sets (DATA_SET_DESC, DATA_SET_TYPE_ID, DATA_SET_DOI, DATA_SET_INPORT_URL, DATA_SET_ACCESS_URL, DATA_SET_ARCHIVE_URL, CRUISE_LEG_ID, DATA_SET_STATUS_ID) values ('2019 MOUSS Data Set', (SELECT DATA_SET_TYPE_ID FROM CCD_DATA_SET_TYPES WHERE DATA_SET_TYPE_NAME = 'MOUSS Video'), '', 'https://inport.nmfs.noaa.gov/inport/item/99999', '', '', (SELECT CRUISE_LEG_ID FROM CCD_CRUISE_LEGS where leg_name = 'SE-19-06'), (SELECT DATA_SET_STATUS_ID FROM CCD_DATA_SET_STATUS where status_code = 'QC'));
