/************************************************************************************
 Filename   : recompile_CTD_objects.sql
 Purpose    : Automated script for recompiling CTD objects after CCD DVM verification tests are executed (causes invalid dependent CTD objects)
************************************************************************************/
SET FEEDBACK OFF
SET TRIMSPOOL ON
SET VERIFY OFF
SET SQLBLANKLINES ON
SET AUTOCOMMIT OFF
SET EXITCOMMIT OFF
SET TERMOUT ON
--SET ECHO ON

WHENEVER SQLERROR EXIT 1
WHENEVER OSERROR  EXIT 1


PROMPT Please provide credentials in the form: USER@TNS/PASSWORD when using a TNS Name:
SET DEFINE ON

-- Provide credentials in the form: USER@TNS/PASSWORD when using a TNS Name
-- Provide credentials in the form: USER/PASSWORD@HOSTNAME/SID when specifying hostname and SID values
DEFINE apps_credentials=&1
CONNECT &apps_credentials

SET ECHO ON;
SET TERMOUT ON;

ALTER VIEW CTD_CAST_CRUISES_V COMPILE;
ALTER VIEW CTD_CAST_FILES_V COMPILE;
ALTER VIEW CTD_CAST_FILE_DATA_V COMPILE;
ALTER VIEW CTD_CAST_FILE_SUMMARY_V COMPILE;
ALTER VIEW CTD_CRUISE_LEG_SUMM_RPT_V COMPILE;
ALTER VIEW CTD_FILE_CASTS_V COMPILE;
ALTER VIEW CTD_FILE_CAST_ISS_CNT_V COMPILE;
ALTER VIEW CTD_FILE_CAST_ISS_RPT_V COMPILE;
ALTER VIEW CTD_FILE_CAST_ISS_V COMPILE;
ALTER VIEW CTD_FILE_CAST_NO_ERR_V COMPILE;
ALTER VIEW CTD_FILE_DVM_EVAL_RPT_V COMPILE;
ALTER VIEW CTD_FILE_DVM_RULES_RPT_V COMPILE;
ALTER VIEW CTD_FILE_DVM_RULE_EVAL_RPT_V COMPILE;
ALTER VIEW CTD_FILE_DVM_RULE_EVAL_V COMPILE;
ALTER VIEW CTD_PROC_DATA_NO_ERR_V COMPILE;
ALTER VIEW CTD_QC_CAST_FILES_V COMPILE;
ALTER VIEW CTD_QC_CAST_FILE_SUMMARY_V COMPILE;
ALTER VIEW CTD_QC_CAST_STATIONS_V COMPILE;
ALTER VIEW CTD_QC_CRUISE_CAST_INFO_V COMPILE;
ALTER VIEW CTD_QC_DUP_CASTS_V COMPILE;
ALTER VIEW CTD_QC_FILES_V COMPILE;
ALTER VIEW CTD_YRLY_SUMM_RPT_V COMPILE;

ALTER PACKAGE CTD_DVM_PKG COMPILE;
ALTER PACKAGE CTD_PKG COMPILE;



DISCONNECT;

EXIT;
